# Conexión a Neon.tech (Producción/Nube)
spring.datasource.url=jdbc:postgresql://ep-twilight-lake-ahbp5t5u.c-3.us-east-1.aws.neon.tech/neondb?sslmode=require
spring.datasource.username=neondb_owner
spring.datasource.password=npg_pdmDqPtT56Bz

# Configuraciones de Hibernate (puedes mantener las que ya tenías, por lo general son estas)
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true