# 1. Credenciales de la Base de Datos (Driver JDBC)
# Asumo que llamaste a tu base de datos 'cafe_erp'. Si le pusiste otro nombre, cámbialo aquí.
spring.datasource.url=jdbc:postgresql://localhost:5432/cafeNasun_erp
spring.datasource.username=postgres
spring.datasource.password=Lozyplus2005@
spring.datasource.driver-class-name=org.postgresql.Driver

# 2. Configuración de JPA / Hibernate (El ORM de Java)
# 'none' le dice a Java: "No intentes crear las tablas, yo ya las creé con mi script DDL"
spring.jpa.hibernate.ddl-auto=none

# 3. Consola y Depuración (Opcional pero muy recomendado)
# Esto imprimirá en la consola las sentencias SQL que Java ejecute por debajo
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true