# Conexión a Base de Datos - Parametrizada por seguridad (Variables de entorno)
# Configura estas variables en tu entorno de producción (Render, etc.)
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/coffedb}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:postgres}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:postgres}

# Configuraciones de Hibernate (eliminada la declaración explícita de dialecto por deprecación)
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.open-in-view=false